### ISSUE TITLE
I have an issue with import the package

### ISSUE THREAD

**Issue by YaldaAmidi227** [ibmm-unibe-ch/TemBERTure#1]
I downloaded the package and installed it without any error but when I want to import it I get this error: 
>>> from temBERTure import TemBERTure
Segmentation fault

Could you please help me how can I solve this issue?

**Comment by Ch-rode** [comment]
Hi @YaldaAmidi227 ! Thanks for using TemBERTure.

Did you follow the downloading instructions?

```
git clone https://github.com/ibmm-unibe-ch/TemBERTure.git
cd TemBERTure
git filter-branch --subdirectory-filter temBERTure -- --all
```
After running these commands, you should have the temBERTure.py file inside the TemBERTure folder. This is the file that the import statement is referring to.
Let me know

`

**Comment by YaldaAmidi227** [comment]
> Hi @YaldaAmidi227 ! Thanks for using TemBERTure.
> 
> Did you follow the downloading instructions?
> 
> ```
> git clone https://github.com/ibmm-unibe-ch/TemBERTure.git
> cd TemBERTure
> git filter-branch --subdirectory-filter temBERTure -- --all
> ```
> 
> After running these commands, you should have the temBERTure.py file inside the TemBERTure folder. This is the file that the import statement is referring to. Let me know
> 
> `

Hi, Yes I have temBERTure.py in the path but when I want to import temBERTure I have "Segmentation fault" error.

**Comment by YaldaAmidi227** [comment]
> Hi @YaldaAmidi227 ! Thanks for using TemBERTure.
> 
> Did you follow the downloading instructions?
> 
> ```
> git clone https://github.com/ibmm-unibe-ch/TemBERTure.git
> cd TemBERTure
> git filter-branch --subdirectory-filter temBERTure -- --all
> ```
> 
> After running these commands, you should have the temBERTure.py file inside the TemBERTure folder. This is the file that the import statement is referring to. Let me know
> 
> `

Hi , 
Yes I downloaded it and I have temBERTure.oy file inside the TemBERTure folder. but when I

**Comment by YaldaAmidi227** [comment]
> Hi @YaldaAmidi227 ! Thanks for using TemBERTure.
> 
> Did you follow the downloading instructions?
> 
> ```
> git clone https://github.com/ibmm-unibe-ch/TemBERTure.git
> cd TemBERTure
> git filter-branch --subdirectory-filter temBERTure -- --all
> ```
> 
> After running these commands, you should have the temBERTure.py file inside the TemBERTure folder. This is the file that the import statement is referring to. Let me know
> 
> `

Hi I finally could import it :) 
my fault was I had removed some lines in requirement.txt "exceptiongroup @ file:///croot/exceptiongroup_1706031385326/work
mkl-fft @ file:///croot/mkl_fft_1695058164594/work
mkl-random @ file:///croot/mkl_random_1695059800811/work
Pillow @ file:///croot/pillow_1696580024257/work
six @ file:///tmp/build/80754af9/six_1644875935023/work
types-python-dateutil==2.8.19.20240106
typing_extensions @ file:///croot/typing_extensions_1705599297034/work" because I couldn't instal it by condo, now I returned back them and installed it again with pip and it's done :)

Thanks for your help
