### ISSUE TITLE
Conda and pip environment installation failure to parse requirements.txt

### ISSUE THREAD

**Issue by ShellHeadBash** [ibmm-unibe-ch/TemBERTure#4]
Hi I've followed the download instructions and cloned the git directory but attempting to install both the Conda and pip environments fails with the respective messages:
- Conda: "CondaValueError: could not parse 'exceptiongroup @ file:///croot/exceptiongroup_1706031385326/work' in requirements.txt"
- pip: "ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/croot/exceptiongroup_1706031385326/work'"
Removing the "@ file :/// ... " from the exceptiongroup package line in the requirements.txt solves this but then the issue repeats for each other package line in the requirements.txt file that has this "@ file:///croot ..." appended to it.

This was on the latest version of Ubuntu Desktop as of 19.08.24 and with Python 3.12 and the latest version of Conda

**Comment by Ch-rode** [comment]
Dear @ShellHeadBash ,
thanks for using TemBERTure !
When I ran pip freeze to create the requirements file, it saved the paths to local libraries in my environment. You can manually remove the entries that start with file:/// from your requirements.txt file. Alternatively, I have edited the requirements file myself and removed these entries, also for next users. You should not encounter any issues now.

I recommend using Python 3.9 for optimal compatibility.
Let me know

**Comment by ShellHeadBash** [comment]
Hi, thank you for the reply! Unfortunately I still encounter an issue. Here's the message: 
"
$ conda install --file requirements.txt
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: - warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
| 
"
Attempting this instead also fails:
$ conda create --name TemBERTure --file requirements.txt python=3.9.18

With a more extensive error message starting:
"
LibMambaUnsatisfiableError: Encountered problems while solving:
"
where the rest of the message lists this but for every package:
"
  - nothing provides requested yarl 1.9.4
"

Thanks for your help!

**Comment by Ch-rode** [comment]
It worked for me. Try to use pip install instead of conda install.
i.e.
```
conda  create --name debug python==3.9
conda activate debug
pip install -r requirements.txt
```

**Comment by ShellHeadBash** [comment]
Hi,

Thank you I've followed what you did and it's working perfectly! Looking forward to experimenting with it.

Thank you

**Comment by Ch-rode** [comment]
@ShellHeadBash Thank you for using TemBERTure. Let us know if you encounter any other issues.
